# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apps/common/proto/task.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61pps/common/proto/task.proto\x12\x04task\"\xcb\x01\n\x08PlanInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\ttask_name\x18\x02 \x01(\t\x12\x11\n\ttask_type\x18\x03 \x01(\t\x12\x12\n\ntask_group\x18\x04 \x01(\t\x12\x13\n\x0btask_config\x18\x05 \x01(\t\x12\x18\n\x10task_data_source\x18\x06 \x01(\t\x12\x1e\n\x16task_data_source_label\x18\x07 \x01(\t\x12\x12\n\nis_crontab\x18\x08 \x01(\t\x12\x16\n\x0e\x63rontab_string\x18\t \x01(\t\"\xf5\x01\n\x08TaskInfo\x12\x17\n\x0fjob_instance_id\x18\x01 \x01(\t\x12\x11\n\ttask_name\x18\x02 \x01(\t\x12\x11\n\ttask_type\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x05\x12\x18\n\x10progress_percent\x18\x05 \x01(\x05\x12\x10\n\x08progress\x18\x06 \x01(\t\x12\x10\n\x08\x61\x63\x63uracy\x18\x07 \x01(\x02\x12\x0f\n\x07message\x18\x08 \x01(\t\x12\x13\n\x0bresult_file\x18\t \x01(\t\x12\x12\n\nstart_time\x18\n \x01(\t\x12\x10\n\x08\x65nd_time\x18\x0b \x01(\t\x12\x10\n\x08username\x18\x0c \x01(\t\"H\n\nRunRequest\x12\x1c\n\x04plan\x18\x01 \x01(\x0b\x32\x0e.task.PlanInfo\x12\x1c\n\x04task\x18\x02 \x01(\x0b\x32\x0e.task.TaskInfo\"8\n\x0bStopRequest\x12\x17\n\x0fjob_instance_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"T\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x1c\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x0e.task.TaskInfo\"X\n\x0cListResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x1c\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x0e.task.TaskInfo2\x93\x01\n\x0bTaskService\x12)\n\x03Run\x12\x10.task.RunRequest\x1a\x0e.task.Response\"\x00\x12+\n\x04Stop\x12\x11.task.StopRequest\x1a\x0e.task.Response\"\x00\x12,\n\x04List\x12\x0e.task.TaskInfo\x1a\x12.task.ListResponse\"\x00\x42\x08Z\x06.;taskb\x06proto3')



_PLANINFO = DESCRIPTOR.message_types_by_name['PlanInfo']
_TASKINFO = DESCRIPTOR.message_types_by_name['TaskInfo']
_RUNREQUEST = DESCRIPTOR.message_types_by_name['RunRequest']
_STOPREQUEST = DESCRIPTOR.message_types_by_name['StopRequest']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_LISTRESPONSE = DESCRIPTOR.message_types_by_name['ListResponse']
PlanInfo = _reflection.GeneratedProtocolMessageType('PlanInfo', (_message.Message,), {
  'DESCRIPTOR' : _PLANINFO,
  '__module__' : 'apps.common.proto.task_pb2'
  # @@protoc_insertion_point(class_scope:task.PlanInfo)
  })
_sym_db.RegisterMessage(PlanInfo)

TaskInfo = _reflection.GeneratedProtocolMessageType('TaskInfo', (_message.Message,), {
  'DESCRIPTOR' : _TASKINFO,
  '__module__' : 'apps.common.proto.task_pb2'
  # @@protoc_insertion_point(class_scope:task.TaskInfo)
  })
_sym_db.RegisterMessage(TaskInfo)

RunRequest = _reflection.GeneratedProtocolMessageType('RunRequest', (_message.Message,), {
  'DESCRIPTOR' : _RUNREQUEST,
  '__module__' : 'apps.common.proto.task_pb2'
  # @@protoc_insertion_point(class_scope:task.RunRequest)
  })
_sym_db.RegisterMessage(RunRequest)

StopRequest = _reflection.GeneratedProtocolMessageType('StopRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPREQUEST,
  '__module__' : 'apps.common.proto.task_pb2'
  # @@protoc_insertion_point(class_scope:task.StopRequest)
  })
_sym_db.RegisterMessage(StopRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'apps.common.proto.task_pb2'
  # @@protoc_insertion_point(class_scope:task.Response)
  })
_sym_db.RegisterMessage(Response)

ListResponse = _reflection.GeneratedProtocolMessageType('ListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESPONSE,
  '__module__' : 'apps.common.proto.task_pb2'
  # @@protoc_insertion_point(class_scope:task.ListResponse)
  })
_sym_db.RegisterMessage(ListResponse)

_TASKSERVICE = DESCRIPTOR.services_by_name['TaskService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006.;task'
  _PLANINFO._serialized_start=39
  _PLANINFO._serialized_end=242
  _TASKINFO._serialized_start=245
  _TASKINFO._serialized_end=490
  _RUNREQUEST._serialized_start=492
  _RUNREQUEST._serialized_end=564
  _STOPREQUEST._serialized_start=566
  _STOPREQUEST._serialized_end=622
  _RESPONSE._serialized_start=624
  _RESPONSE._serialized_end=708
  _LISTRESPONSE._serialized_start=710
  _LISTRESPONSE._serialized_end=798
  _TASKSERVICE._serialized_start=801
  _TASKSERVICE._serialized_end=948
# @@protoc_insertion_point(module_scope)
