# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from apps.common.proto import task_pb2 as apps_dot_common_dot_proto_dot_task__pb2


class TaskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_unary(
                '/task.TaskService/Run',
                request_serializer=apps_dot_common_dot_proto_dot_task__pb2.RunRequest.SerializeToString,
                response_deserializer=apps_dot_common_dot_proto_dot_task__pb2.Response.FromString,
                )
        self.Stop = channel.unary_unary(
                '/task.TaskService/Stop',
                request_serializer=apps_dot_common_dot_proto_dot_task__pb2.StopRequest.SerializeToString,
                response_deserializer=apps_dot_common_dot_proto_dot_task__pb2.Response.FromString,
                )
        self.List = channel.unary_unary(
                '/task.TaskService/List',
                request_serializer=apps_dot_common_dot_proto_dot_task__pb2.TaskInfo.SerializeToString,
                response_deserializer=apps_dot_common_dot_proto_dot_task__pb2.ListResponse.FromString,
                )


class TaskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=apps_dot_common_dot_proto_dot_task__pb2.RunRequest.FromString,
                    response_serializer=apps_dot_common_dot_proto_dot_task__pb2.Response.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=apps_dot_common_dot_proto_dot_task__pb2.StopRequest.FromString,
                    response_serializer=apps_dot_common_dot_proto_dot_task__pb2.Response.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=apps_dot_common_dot_proto_dot_task__pb2.TaskInfo.FromString,
                    response_serializer=apps_dot_common_dot_proto_dot_task__pb2.ListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'task.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/task.TaskService/Run',
            apps_dot_common_dot_proto_dot_task__pb2.RunRequest.SerializeToString,
            apps_dot_common_dot_proto_dot_task__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/task.TaskService/Stop',
            apps_dot_common_dot_proto_dot_task__pb2.StopRequest.SerializeToString,
            apps_dot_common_dot_proto_dot_task__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/task.TaskService/List',
            apps_dot_common_dot_proto_dot_task__pb2.TaskInfo.SerializeToString,
            apps_dot_common_dot_proto_dot_task__pb2.ListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
